version: "3"
services:
  servicemon:
    container_name: servicemon
    restart: always
    image: nobio/servicemon:latest
    environment:
    - MONGODB_USER=httpstatus-user
    - MONGODB_PASSWORD=a57XDbVIlpVHNjuF
    - DATABASE_MONGO_URI=nobiocluster.arj0i.mongodb.net/http-status?retryWrites=true&w=majority
    - DATABASE_MONGO_PROTOCOL=mongodb+srv
    #volumes:
    ports:
      - "28090:28090"
