name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$HETZNER_SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$HETZNER_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.HETZNER_SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.HETZNER_SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Deploy to Server
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          SERVER_USER: root
          SERVER_IP: 88.198.110.159
          APP_DIR: /home/nobio/container/tmp
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          ls -la 
          "