name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.HETZNER_SSH_PRIVATE_KEY}}
          #SSH_KNOWN_HOSTS: ${{secrets.HETZNER_SSH_KNOWN_HOSTS}}
          SSH_KNOWN_HOSTS: 88.198.110.159
          SSH_KEY_PATH: .ssh/private.key
        run: |
          mkdir -p .ssh/
          chmod 700 .ssh
          #touch .ssh/private.key
          echo "$SSH_PRIVATE_KEY" > .ssh/private.key
          sudo chmod 600 .ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > .ssh/known_hosts
          ls -la .ssh/

      - name: Deploy to Server
        env:
          SSH_KEY_PATH: .ssh/private.key
          SERVER_USER: nobio
          SERVER_IP: 88.198.110.159
          APP_DIR: /home/nobio/container/tmp
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          ls -la 
          "