# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Service Monitor

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #node-version: [14.x, 16.x, 17.x]
        node-version: [v16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: ServiceMon ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y python
      - run: npm ci
      - run: npm run build --production
      - run: touch monitor.db monitor.db.0
      - run: chmod g+rw monitor.db*

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nobio/servicemon:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
